### ISSUE TITLE
Api??

### ISSUE THREAD

**Issue by Tony96Sosa** [FacundoBettella/memory-game#1]
Se rompe al iniciar axios, supongo que viene por esta variable de entorno REACT_APP_API_ENDPOINT, de donde saco esa variable?

**Comment by Tony96Sosa** [comment]
ya encontre la url de la api, estaba en uno de tus commits jeje

**Comment by FacundoBettella** [comment]
Bien ahi! La puse en .env porque esa api la saque de un challlenge que hice. Cualquier cosa avisame!
